### ISSUE TITLE
ValueError: setting an array element with a sequence

### ISSUE THREAD

**Issue by marade** [zheminzhou/PEPPA#1]
After running for a few hours without issues I get this:

Traceback (most recent call last):
  File "/home/ubuntu/PEPPA/PEPPA.py", line 1809, in <module>
    ortho(sys.argv[1:])
  File "/home/ubuntu/PEPPA/PEPPA.py", line 1804, in ortho
    write_output(params['prefix'], params['prediction'], genomes, genes, encodes, old_predictions, params['pseudogene'], params['untrusted'], params['gtable'],
params.get('clust', None), params.get('self_bsn', None))
  File "/home/ubuntu/PEPPA/PEPPA.py", line 1317, in write_output
    prediction = pd.DataFrame(np.vstack([prediction, np.array(list(old_to_add))])).sort_values(by=[5,9]).values
ValueError: setting an array element with a sequence

Any ideas?

**Comment by zheminzhou** [comment]
I have updated the code to solve this error. Please pull down the latest code and have a try. Many thanks for the report.
