### ISSUE TITLE
Understanding Peppan output

### ISSUE THREAD

**Issue by lalalagartija** [zheminzhou/PEPPA#15]
Hi, 
I wonder if there is a way to visualize your output files so that we could grasp the different stages of the analysis. I am particularily interested in the synteny.Prediction file. Is it an equivalent of what we could get from Mauve ? 

Thank you very much in advance,

**Comment by zheminzhou** [comment]
Unfortunately synteny.prediction is quite different from Mauve result. It does not infer synteny blocks of genes. Instead, it is a ortholog prediction based on local synteny. 

And currently there is no visualization tool for the internal results by PEPPAN. Sorry

**Comment by tauqeer9** [comment]
Very nice tool for pangenome analysis, worked smoothly as described. Is there any script to plot rarefaction curve from "gene_content.curve" or "gene_content.Rtab" file as shown in the Fig.4 of the Genome Research paper?

Thanks

Tauqeer
